version: "3"
services:
  api:
    depends_on:
      - db
    build: 
      context: ./apitest
    ports:
      - "8080:8080"
    restart : always
    volumes:
      - ./apitest:/go/src/apitest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    links:
      - "db"
  db:
    build:
      context: ./sqltest
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: root
       MYSQL_PASSWORD: root

